using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace DSUgrupp2.Data
{
    /// <summary>
    /// Autogenerated class for saving LoginDbContext to DB.
    /// </summary>
    public class LoginDbContext : IdentityDbContext
    {
        private readonly DbContextOptions<LoginDbContext> _options;

        public LoginDbContext(DbContextOptions<LoginDbContext> options) : base(options)
        {
            _options = options;
        }
        protected override void OnModelCreating(ModelBuilder modelbuilder)
        {
            base.OnModelCreating(modelbuilder);
        }
    }
}
